wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.11
    code_path: code/QuantumControl/hyperparam_tuner.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.11
    start_time: 1682397835.958484
    t:
      1:
      - 1
      - 2
      - 3
      - 35
      - 55
      2:
      - 1
      - 2
      - 3
      - 35
      - 55
      3:
      - 13
      - 16
      - 23
      - 35
      4: 3.9.11
      5: 0.13.11
      8:
      - 5
num-envs:
  desc: null
  value: 16
num-minibatches:
  desc: null
  value: 1
num-steps:
  desc: null
  value: 128
total-timesteps:
  desc: null
  value: 100000
update-epochs:
  desc: null
  value: 4
